services:
  - type: web
    name: propml-api
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn src.serving.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODELS_DIR
        value: models
      - key: ANALYTICS_DIR
        value: reports/analytics
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /health
    autoDeploy: true